### ISSUE TITLE
yarn add edge-currency-accountbased fails

### ISSUE THREAD

**Issue by wolverineks** [EdgeApp/edge-currency-accountbased#150]
running `yarn add edge-currency-accountbased` fails every time with the last bit looking like this:
```bash
2 warnings and 10 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kevinsullivan/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/kevinsullivan/.nvm/versions/node/v13.6.0/bin/node" "/Users/kevinsullivan/.nvm/versions/node/v13.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kevinsullivan/Desktop/wolverineks/edge-react-hooks/edge-hooks-react-dom/node_modules/scrypt
```

**Comment by swansontec** [comment]
This is caused by a too-new version of Node.js. I think we have some dependencies that don't work on Node v11 or higher. Ideally, we would get rid of these dependencies so the build stops failing.

**Comment by wolverineks** [comment]
bingo, thanks
